name: Build the CLI

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yml"
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          fetch-depth: 0

      - name: Setup JS
        uses: ./.github/actions/setup-js
        with:
          enable-cache: true

      - name: Code Quality
        run: yarn lint
        shell: bash

      - name: Unit Tests
        run: yarn test
        shell: bash

      - name: Build CLI
        run: yarn build:prod
        shell: bash
