name: Build the CLI

on:
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yml"
  push:
    branches: [main]
    paths:
      - "src/**"
      - "package.json"
      - ".github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn
      - name: Code Quality
        run: yarn lint
      - name: Unit Tests
        run: yarn test
      - run: yarn build:prod
