name: Publish to NPM
description: Build and publish library to NPM

on:
  workflow_call:
    inputs:
      increment:
        description: "Release increment (major|minor|patch)"
        type: string
      pre_release:
        description: "Is release candidate?"
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install modules
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn
      - name: Prepare build
        run: |
          yarn prepare
      - name: Run Release
        shell: bash
        run: |
          git config --global user.email "luigimario1913@gmail.com"
          git config --global user.name "Mateusz Mędrek"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          if [[ ${{ inputs.pre_release }} == true ]]
          then
            yarn release --preRelease=rc --ci --npm.skipChecks
          else
            yarn release --increment=${{ inputs.increment }} --ci --npm.skipChecks
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
