name: Pre-release to NPM

on: 
  workflow_dispatch:

jobs:
  npm-pre-release:
    uses: mateusz1913/vision-camera-plugin-builder/.github/workflows/npm-release-template.yml@main
    with:
      pre_release: true
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
