name: Patch release to NPM

on: workflow_dispatch

jobs:  
  npm-release-patch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Publish patch release
        uses: mateusz1913/vision-camera-plugin-builder/.github/workflow-templates/npm-release-template.yml@main
        with:
          increment: "patch"
