name: Patch release to NPM

on: 
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: |
          echo "---- npm token: $NPM_TOKEN ----"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  npm-release-patch:
    uses: mateusz1913/vision-camera-plugin-builder/.github/workflows/npm-release-template.yml@main
    with:
      increment: patch
