name: Minor release to NPM

on: 
  workflow_dispatch:

jobs:
  npm-release-minor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Publish minor release
        uses: mateusz1913/vision-camera-plugin-builder/.github/workflows/npm-release-template.yml@main
        with:
          increment: minor
