name: Major release to NPM

on: 
  workflow_dispatch:

jobs:
  npm-release-major:
    uses: mateusz1913/vision-camera-plugin-builder/.github/workflows/npm-release-template.yml@main
    with:
      increment: major
